from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
import openai
import os
import json
import re
from sqlalchemy.orm import Session
from app.database import get_db
from app.models import AnkiWord
from app.auth.auth_handler import get_current_user
from app.models import User

router = APIRouter()

# Set your OpenAI API key (recommended: use environment variable)
openai.api_key = os.getenv("OPENAI_API_KEY")
# openai.api_key = "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"
class PromptRequest(BaseModel):
    prompt: str
    max_tokens: int = 100
@router.post("/get-meaning/{language}")
def get_meaning(language: str, request: PromptRequest, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    if not openai.api_key:
        raise HTTPException(status_code=500, detail="OpenAI API key not configured")
    try:
        prompt = (
            f"Return the meaning of the word '{request.prompt}' in {language} as a JSON object. "
            f"The JSON should have two fields: 'word' and 'meaning'. The meaning should be in the {language}. "
            "Only return the JSON object, no extra text."
        )
        print("OpenAI request prompt:", prompt)  # For debugging
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            max_tokens=request.max_tokens
        )
        raw_content = response.choices[0].message.content.strip()
        # Remove code block markers if present
        cleaned = re.sub(r"^```(?:json)?|```$", "", raw_content.strip(), flags=re.MULTILINE).strip()
        try:
            meaning_json = json.loads(cleaned)
        except Exception:
            raise HTTPException(status_code=500, detail="OpenAI did not return valid JSON: " + raw_content)
        return meaning_json
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/gen-story/{language}")
def ai_prompt(language: str, request: PromptRequest, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    if not openai.api_key:
        raise HTTPException(status_code=500, detail="OpenAI API key not configured")
    try:
        words = db.query(AnkiWord).filter(AnkiWord.language == language).all()
        wordStr = []
        if not words:
            wordStr = []
        else: 
            wordStr = [word.words for word in words]
            # translateStr = [word.translated for word in words]
            # wordStr = wordStr + translateStr
            # wordStr = [word.translated for word in words]
        
        if len(wordStr) > 50:
            prompt = (
                "Story title is "+ request.prompt + ". " +
                "Generate a story in " + language +
                " using ONLY these words: " + ", ".join(wordStr) +
                ". Do not use any other words, but 5 new words are enable. The story should be less than 500 characters."
            )
        else:
            prompt = (
                "Story title is "+ request.prompt + ". " +
                "Generate a very simple story in " + language +
                " with less than 200 characters."
            )
        print("OpenAI request prompt:", prompt)  # For debugging
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": prompt  # <-- use "content" here
                }
            ]
        )
        return {"response": response.choices[0].message.content.strip()}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/get-quizes/{language}")
def get_quizzes(language: str, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    if not openai.api_key:
        raise HTTPException(status_code=500, detail="OpenAI API key not configured")
    try:
        words = db.query(AnkiWord.words).all()
        wordStr = []
        if not words:
            wordStr = []
        else: 
            wordStr = [word.words for word in words]  # CORRECT
        prompt = (
            "Generate " + language + " language learning quiz questions. "
            "Each quiz should be a JSON object with 'question', 'options' (a list of 4), and 'answer' and 'meaning' of answer. "
            "And the answer should be one of the options and not be into this words: " + ", ".join(wordStr) + ". "
            "And the options should be randomly generated. "
            "And the quiz difficulty should be generated by this words length: " + str(len(wordStr)) + ". "
            "Return ONLY a JSON array of 20 such objects, with no explanation or extra text."
        )
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        raw_content = response.choices[0].message.content.strip()
        print("OpenAI raw response:", raw_content)  # For debugging

        # Remove code block markers if present
        cleaned = re.sub(r"^```(?:json)?|```$", "", raw_content.strip(), flags=re.MULTILINE).strip()

        try:
            quizzes = json.loads(cleaned)
        except Exception:
            raise HTTPException(status_code=500, detail="OpenAI did not return valid JSON: " + raw_content)
        return quizzes
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

